"""SVG fill -> polygons, preserving paths, transforms, subpaths and holes.

Scope: filled path SVG generated by VTracer, not arbitrary SVG artwork.
Unsupported rendering features fail explicitly rather than becoming geometry.
"""
from dataclasses import dataclass
import math
import re
import xml.etree.ElementTree as ET
import numpy as np
from shapely.geometry import Polygon, MultiPolygon, LineString, box
from shapely.ops import polygonize, unary_union
from .pinch import separate_touching_rings


@dataclass
class PathRings:
    rings: list
    fill_rule: str = "nonzero"


class ParsedVector(list):
    """Flat ring list for legacy callers, with path boundaries/fill semantics."""
    def __init__(self, groups, width=None, height=None, tolerance=0.1):
        super().__init__(r for g in groups for r in g.rings)
        self.groups = groups
        self.width = width
        self.height = height
        self.tolerance = tolerance


def _distance_to_segment(p, a, b):
    p, a, b = map(lambda x: np.asarray(x, dtype=float), (p, a, b))
    v = b - a
    denom = float(v @ v)
    t = 0.0 if denom == 0 else float(np.clip((p - a) @ v / denom, 0, 1))
    return float(np.linalg.norm(p - (a + t * v)))


def _flatten_cubic(p0, p1, p2, p3, tolerance, depth=0, max_depth=24):
    """Bound with both control points, not a midpoint test (fails on S curves)."""
    if not math.isfinite(tolerance) or tolerance <= 0:
        raise ValueError("Flatten tolerance must be positive and finite")
    error = max(_distance_to_segment(p1, p0, p3),
                _distance_to_segment(p2, p0, p3))
    if error <= tolerance:
        return [tuple(p3)]
    if depth >= max_depth:
        raise ValueError("Curve subdivision budget exhausted; tolerance not met")
    a, b, c = (np.asarray(p, dtype=float) for p in (p0, p1, p2))
    d = np.asarray(p3, dtype=float)
    ab, bc, cd = (a + b) / 2, (b + c) / 2, (c + d) / 2
    abc, bcd = (ab + bc) / 2, (bc + cd) / 2
    mid = (abc + bcd) / 2
    return (_flatten_cubic(a, ab, abc, mid, tolerance, depth + 1, max_depth)
            + _flatten_cubic(mid, bcd, cd, d, tolerance, depth + 1, max_depth))


_NUMBER = r"[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?"


def _numbers(text):
    if re.sub(_NUMBER, "", text).strip(" ,\t\r\n"):
        raise ValueError(f"Invalid numeric list: {text!r}")
    values = [float(x) for x in re.findall(_NUMBER, text)]
    if not all(math.isfinite(x) for x in values):
        raise ValueError("Nonfinite SVG coordinates")
    return values


def _transform(text):
    """SVG transform list (column vectors). Paths themselves are NEVER tokenized."""
    total = np.eye(3)
    pos = 0
    for match in re.finditer(r"([A-Za-z]+)\s*\(([^)]*)\)", text):
        if text[pos:match.start()].strip(" ,\t\n\r"):
            raise ValueError("Malformed SVG transform")
        name, values = match[1], _numbers(match[2])
        m = np.eye(3)
        if name == "matrix" and len(values) == 6:
            a, b, c, d, e, f = values
            m = np.array([[a, c, e], [b, d, f], [0, 0, 1.]])
        elif name == "translate" and len(values) in (1, 2):
            m[0, 2] = values[0]
            m[1, 2] = values[1] if len(values) == 2 else 0
        elif name == "scale" and len(values) in (1, 2):
            m[0, 0] = values[0]
            m[1, 1] = values[-1]
        elif name == "rotate" and len(values) in (1, 3):
            angle = math.radians(values[0])
            c, s = math.cos(angle), math.sin(angle)
            m[:2, :2] = [[c, -s], [s, c]]
            if len(values) == 3:
                center = np.array(values[1:])
                m[:2, 2] = center - m[:2, :2] @ center
        elif name in ("skewX", "skewY") and len(values) == 1:
            tangent = math.tan(math.radians(values[0]))
            m[0, 1] = tangent if name == "skewX" else 0
            m[1, 0] = tangent if name == "skewY" else 0
        else:
            raise ValueError(f"Unsupported SVG transform: {name}")
        total = total @ m
        pos = match.end()
    if text[pos:].strip(" ,\t\n\r"):
        raise ValueError("Malformed SVG transform")
    if not np.isfinite(total).all():
        raise ValueError("Nonfinite SVG transform")
    return total


def _clean_ring(points):
    cleaned = []
    for x, y in points:
        p = (float(x), float(y))
        if not all(map(math.isfinite, p)):
            raise ValueError("Nonfinite path coordinate")
        if not cleaned or p != cleaned[-1]:
            cleaned.append(p)
    if len(cleaned) > 1 and cleaned[-1] == cleaned[0]:
        cleaned.pop()
    return cleaned if len(set(cleaned)) >= 3 else []


def _flatten_path(path, tolerance, matrix=None):
    from svg.path import Move, Line, CubicBezier, QuadraticBezier, Close
    matrix = np.eye(3) if matrix is None else matrix

    def point(z):
        q = matrix @ np.array([z.real, z.imag, 1.])
        return (float(q[0]), float(q[1]))

    rings, current = [], []

    def flush():
        ring = _clean_ring(current)
        if ring:
            rings.append(ring)
        current.clear()

    for seg in path:
        if isinstance(seg, Move):
            flush()
            current.append(point(seg.end))
        elif isinstance(seg, Close):  # Check before line-like segments.
            flush()
        elif isinstance(seg, Line):
            if not current:
                current.append(point(seg.start))
            current.append(point(seg.end))
        elif isinstance(seg, (CubicBezier, QuadraticBezier)):
            p0, p3 = point(seg.start), point(seg.end)
            if not current:
                current.append(p0)
            if isinstance(seg, CubicBezier):
                p1, p2 = point(seg.control1), point(seg.control2)
            else:
                q = np.array(point(seg.control))
                p1 = np.array(p0) + (2 / 3) * (q - p0)
                p2 = np.array(p3) + (2 / 3) * (q - p3)
            current.extend(_flatten_cubic(p0, p1, p2, p3, tolerance))
        else:
            # VTracer emits line/quadratic/cubic paths, not elliptical arcs.
            raise ValueError(f"Unsupported VTracer segment: {type(seg).__name__}")
        if len(current) > 200_000:
            raise ValueError("Path exceeds flattening point budget")
    flush()  # SVG fill implicitly closes open subpaths.
    return rings


def parse_vector(svg, tolerance=0.1):
    from svg.path import parse_path
    if not math.isfinite(tolerance) or tolerance <= 0:
        raise ValueError("Flatten tolerance must be positive and finite")
    if "<!DOCTYPE" in svg.upper() or "<!ENTITY" in svg.upper():
        raise ValueError("DTD/entity declarations are not accepted")
    root = ET.fromstring(svg)
    if root.tag.rsplit("}", 1)[-1] != "svg":
        raise ValueError("Expected SVG root")
    view = _numbers(root.get("viewBox", ""))
    if len(view) != 4 or min(view[2:]) <= 0:
        raise ValueError("A finite positive SVG viewBox is required")
    vx, vy, width, height = view
    # Cropping a padded viewBox means subtracting its origin ONCE.
    origin = np.array([[1., 0, -vx], [0, 1., -vy], [0, 0, 1.]])
    groups = []

    def visit(element, parent_matrix, parent_style, is_root=False):
        tag = element.tag.rsplit("}", 1)[-1]
        if tag in ("title", "desc", "metadata"):
            return
        if tag not in ("svg", "g", "path") or (tag == "svg" and not is_root):
            raise ValueError(f"Unsupported element in binary SVG: {tag}")
        if any(k in element.attrib for k in ("clip-path", "mask", "filter")):
            raise ValueError("Unsupported SVG clipping/mask/filter")
        style = dict(parent_style)
        for key in ("fill", "fill-rule", "stroke", "display", "visibility", "opacity", "fill-opacity"):
            if key in element.attrib:
                style[key] = element.attrib[key]
        for declaration in element.get("style", "").split(";"):
            if declaration.strip():
                key, value = declaration.split(":", 1)
                style[key.strip()] = value.strip()
        if style.get("display") == "none" or style.get("visibility") == "hidden":
            return
        for key in ("opacity", "fill-opacity"):
            if float(style.get(key, "1")) != 1.0:
                raise ValueError("Only opaque binary SVG paths are accepted")
        matrix = parent_matrix @ _transform(element.get("transform", ""))
        if tag == "path":
            fill = style.get("fill", "black").lower().replace(" ", "")
            if fill == "none":
                return
            if fill not in ("black", "#000", "#000000", "rgb(0,0,0)"):
                raise ValueError(f"Expected black binary foreground; found fill={fill}")
            if style.get("stroke", "none") != "none":
                raise ValueError("Stroked paths need stroke expansion before extrusion")
            rule = style.get("fill-rule", "nonzero")
            if rule not in ("nonzero", "evenodd"):
                raise ValueError(f"Unsupported fill-rule: {rule}")
            d = element.get("d")
            if d:
                rings = _flatten_path(parse_path(d), tolerance, matrix)
                if rings:
                    groups.append(PathRings(rings, rule))
        for child in element:
            visit(child, matrix, style)

    visit(root, origin, {}, True)
    if not groups:
        raise ValueError("SVG contains no filled geometry")
    return ParsedVector(groups, width, height, tolerance)


def _winding_at(point, rings):
    x, y = point
    winding = 0
    for ring in rings:
        p = np.asarray(ring, dtype=float)
        q = np.roll(p, -1, axis=0)
        cross = (q[:, 0] - p[:, 0]) * (y - p[:, 1]) - (x - p[:, 0]) * (q[:, 1] - p[:, 1])
        winding += int(np.count_nonzero((p[:, 1] <= y) & (q[:, 1] > y) & (cross > 0)))
        winding -= int(np.count_nonzero((p[:, 1] > y) & (q[:, 1] <= y) & (cross < 0)))
    return winding


def _fill_group(group):
    rings = [_clean_ring(r) for r in group.rings]
    rings = [r for r in rings if r]
    if not rings:
        return Polygon()
    # Polygonize noded linework, then select faces by the ACTUAL SVG fill rule.
    # This implements fill semantics; it is not a make_valid/convex-hull fallback.
    edges = unary_union([LineString(r + [r[0]]) for r in rings])
    material = []
    for face in polygonize(edges):
        test = face.representative_point()
        winding = _winding_at((test.x, test.y), rings)
        keep = winding != 0 if group.fill_rule == "nonzero" else winding % 2 != 0
        if keep:
            material.append(face)
    return unary_union(material) if material else Polygon()


def polygons_to_flat(polygons):
    out = []
    for p in polygons:
        if p.is_empty:
            continue
        if isinstance(p, Polygon):
            out.append(p)
        elif isinstance(p, MultiPolygon):
            out.extend(p.geoms)
        elif p.geom_type == "GeometryCollection":
            # Zero-area viewport contacts have no material to extrude.
            out.extend(polygons_to_flat([g for g in p.geoms if g.area > 0]))
        else:
            raise ValueError(f"Expected polygonal material, not {p.geom_type}")
    return out


def vector_to_polygons(vector, tolerance=None):
    # The optional historical argument cannot re-flatten already sampled rings.
    if tolerance is not None and isinstance(vector, ParsedVector) and tolerance != vector.tolerance:
        raise ValueError("Set flatten tolerance in parse_vector(), not after flattening")
    groups = vector.groups if isinstance(vector, ParsedVector) else [PathRings(vector, "evenodd")]
    # Distinct opaque SVG paths are UNIONED, not XORed with each other.
    material = unary_union([_fill_group(group) for group in groups])
    if isinstance(vector, ParsedVector) and vector.width is not None:
        # Match the declared SVG viewport. No ring is discarded by a heuristic.
        material = material.intersection(box(0, 0, vector.width, vector.height))
    result = polygons_to_flat([material])
    # A traced bitmap can leave two holes sharing a vertex.  Opening those
    # contacts here keeps every asset printable from the moment it is
    # imported, instead of failing later at export (see silhouettes.pinch).
    result = [separate_touching_rings(p) for p in result]
    if not result or any(not p.is_valid or p.area <= 0 for p in result):
        raise ValueError("SVG fill produced no valid positive-area polygons")
    return result
